services:
    jonasarts\Bundle\RegistryBundle\Registry\DoctrineRegistry: 
        arguments: [ "@service_container", "@doctrine.orm.entity_manager" ]

    jonasarts\Bundle\RegistryBundle\Registry\RedisRegistry:
        #arguments: [ "@service_container", "@snc_redis.phpredis.registry" ]
        arguments: [ "@service_container", "@snc_redis.registry" ]

    #jonasarts\Bundle\RegistryBundle\Registry\RegistryInterface:  '@jonasarts\Bundle\RegistryBundle\Registry\RedisRegistry'